### ISSUE TITLE
[Discuss] - other similar extensions

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/wbmExtension#11]
Save To The Wayback Machine
https://chrome.google.com/webstore/detail/save-to-the-wayback-machi/eebpioaailbjojmdbmlpomfgijnlcemk?hl=en

- focus on saving

![https://lh3.googleusercontent.com/4BoTK3NPD0z8xdK2nkfY6opN-phjGpAZVjmYafHfgFefMKzIjbo5y9cc1dOK4nL6ehUQeD_Utg=w640-h400-e365](https://lh3.googleusercontent.com/4BoTK3NPD0z8xdK2nkfY6opN-phjGpAZVjmYafHfgFefMKzIjbo5y9cc1dOK4nL6ehUQeD_Utg=w640-h400-e365)

![https://lh3.googleusercontent.com/4kWNTI9VxYdFmTeeyMI7JY0t9k7aWrgUtzwhiqIBSbhVn3nu2JPjklHfjSF20YNlweUStG37mQ=w640-h400-e365](https://lh3.googleusercontent.com/4kWNTI9VxYdFmTeeyMI7JY0t9k7aWrgUtzwhiqIBSbhVn3nu2JPjklHfjSF20YNlweUStG37mQ=w640-h400-e365)

![https://lh3.googleusercontent.com/QjQTRvUDwh_eTTBo5J9OQ3cUW9S6YahuPwdObq-D_oPn9N_gXfvI_A4R3WveFaryb_K6drRR1M4=w640-h400-e365](https://lh3.googleusercontent.com/QjQTRvUDwh_eTTBo5J9OQ3cUW9S6YahuPwdObq-D_oPn9N_gXfvI_A4R3WveFaryb_K6drRR1M4=w640-h400-e365)

![https://lh3.googleusercontent.com/O8dqbv1sFrwAbkzQxQ87EumBnC6-PcHwqx0CWjQp3cHSy5Nthv7jkQPTPpZqI7p1pxhJH5uvqvU=w640-h400-e365](https://lh3.googleusercontent.com/O8dqbv1sFrwAbkzQxQ87EumBnC6-PcHwqx0CWjQp3cHSy5Nthv7jkQPTPpZqI7p1pxhJH5uvqvU=w640-h400-e365)

![Screen shot 2019-11-20 at 02 03 27](https://user-images.githubusercontent.com/49612/69202608-1a91e880-0b3a-11ea-96a1-7e14f5df5fbd.png)

**Comment by otzbergnet** [comment]
Which of this would be desired functionality in your view? In other words what do we need to do?

The focus on saving is a use case I am not quite getting. I mean I get it, but I don't get why one would focus so much on it. But then again, I am not the target audience :)

**Comment by gingerbeardman** [comment]
The bits of this that I find useful.

- whether page is already archived (would save a wasted trip)
- archive page in background
- ability to select which context menus you want to see

**Comment by gingerbeardman** [comment]
for checking archived status of current page 
https://archive.org/help/wayback_api.php

**Comment by otzbergnet** [comment]
I've aded the page last archived feature in 

![Bildschirmfoto 2019-11-22 um 20 42 57](https://user-images.githubusercontent.com/43129918/69455494-cde02480-0d68-11ea-9bed-eef1a8eb8d15.png)

I have not yet looked at the Chrome Extension to fully understand how they do the archiving in the background. Quite possibly could be as simple as sending the request and watching the response code...

**Comment by otzbergnet** [comment]
So I quickly did an archive action with Charles Proxy and it seems that the tool is simply sending a https://web.archive.org/save/URL_TO_BE_SAVED and then likely watches for the Status Code. Not sure it adds a lot of value. Should we just let our archive page feature happen in the same tag and take the user through the official UX of archive.org?

**Comment by otzbergnet** [comment]
basically, I think we did the one thing that made sense - so closing this for now
