### ISSUE TITLE
[DISCUSS] Should "Save Current page" happen in same tab

### ISSUE THREAD

**Issue by otzbergnet** [otzbergnet/wbmExtension#12]
I tried the Save Current Page - it opened a new tab and then completed the save. For this action, should it rather happen in the same tab?

**Comment by gingerbeardman** [comment]
I think so, current tab.

BUT the Chrome extension I posted does it behind the scenes??

**Comment by otzbergnet** [comment]
I've seen that - I need to install the chrome extension and watch its
background.html to see how they do it :)

**Comment by otzbergnet** [comment]
save page now happens in the tab that you are on - seems more sensible
