### ISSUE TITLE
[Add] Open Oldest snapshot context menu

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/wbmExtension#13]

**Comment by otzbergnet** [comment]
Safari has a curious behavior and that is, it doesn't collapse many context menu items, like Google Chrome does. 

In Chrome, if your extension adds five context menu entries, they are immediately collapsed into a single one.

Adding a third context menu item, is - of course - not an issue, but do we truly want it?  I did read the documentation (well I scanned it) and couldn't find a reference to submenus. So just to be sure, do we truly want a third context menu entry?

**Comment by otzbergnet** [comment]
I went ahead and implemented it despite my concern, but I draw the line at three ;)

**Comment by gingerbeardman** [comment]
I agree.

**Comment by gingerbeardman** [comment]
What are your thoughts on letting these decide which context menus to show?

**Comment by otzbergnet** [comment]
need to figure out if that is possible. The context menu isn't programmatically added, but declaratively via the plist. But there is an eval function, which allows to change titles. Maybe one could hide context menus as well... something to investigate and thus reopen this

**Comment by otzbergnet** [comment]
way easier than I would have thought: validationHandler(true, nil)

I shall look at that tomorrow sometime ;) Thanks for challenging my thoughts, making for better outcomes

**Comment by otzbergnet** [comment]
So there is no a setting section in the containing app, which will allow the user to select which context menu items they would like to show (if any at all). Right now it defaults to all, but I am thinking of setting only the "Page History" command to be on by default. Thoughts?

**Comment by gingerbeardman** [comment]
Yes, I agree because that is the broadest result. Then the user can add/replace with more specific commands should they wish.

Speaking of commands, do you envisage the context menus have "wsm: " at their beginning? I assumed this was for development. I don't think they should have that. Just the text after it is enough. None of the other context menus I have sa which extension they are from.

**Comment by otzbergnet** [comment]
That’sa great point. I am a bit worried that the connect might not be clear... 

So:

No, I don’t think the app should have wbm: in front of the item

Yes, we need to find a way to ensure connection is clear for folk with plenty of extensions

I am not sure how to achieve this :(

Btw: what should we call the extension?

Greetings

Claus

**Comment by gingerbeardman** [comment]
Here are my current custom items on the Safari context menu...

on page:
![Screen shot 2019-11-24 at 20 37 03](https://user-images.githubusercontent.com/49612/69501193-69ed6580-0efa-11ea-8d27-6172a2e5731b.png)

on image:
![Screen shot 2019-11-24 at 20 37 32](https://user-images.githubusercontent.com/49612/69501194-6a85fc00-0efa-11ea-80bc-cd295cb1b605.png)

Signposted labels:
- Reading Queue
- Tab Space
- 1Blocker

Not signposted:
- Myna Translate
- Reverse Image Search

AFAIK we can get away with using Wayback Machine in the name as long as it is not at the beginning. 

Name ideas
- Wayback
- Simple Wayback Machine

So maybe there are two options
1) signpost using short name or acronym, eg.
- Open Newest Snapshot with WBM
- Open Newest Snapshot with Wayback

2) do not signpost, trust we make it clear to the user which context menus are ours through the popover and container app, and maybe call the app something longer
- Open Newest Snapshot

**Comment by otzbergnet** [comment]
I like the idea of using "Wayback" and using signposting in the context menu

* Open Newest Snapshot with Wayback

I need to read up how long subtitles are allowed to be, so we can describe the app:

Wayback - a convenient way to interact with the Internet Archive's Wayback Machine

I have a feeling that this will be too long... but one for tonight.

**Comment by otzbergnet** [comment]
I will move the naming discussion to a new issue
