### ISSUE TITLE
[Discuss] design of popover

### ISSUE THREAD

**Issue by otzbergnet** [otzbergnet/wbmExtension#15]
My addition of the last snapshot date, causes some UI issues - i.e. could look better. What are your thoughts.

I personally think:

buttons top
last snapshot date with save page button
then the URL bar

would very much appreciate some help here :)

**Comment by gingerbeardman** [comment]
Will take a look!

**Comment by gingerbeardman** [comment]
Have made a few small tweaks:

- switch off focus ring on buttons
- align width of enter label
- change URL placeholder to an actual URL

**Comment by gingerbeardman** [comment]
I was wondering about making it look more like a share menu.

Could we use Emoji as icons? Really not sure about this but:

💾 Save Current Page
🗓 Show Page History
🐓 Open Oldest Snapshot
🐥 Open Newest Snapshot
🗂 Show Domain Files
🗃 Show Domain Data

**Comment by gingerbeardman** [comment]
Current comparison

Share:
![Screen shot 2019-11-29 at 17 12 53](https://user-images.githubusercontent.com/49612/69883325-8a873800-12cb-11ea-9b04-5103feb49b2c.png)

WBM:
![Uploading Screen shot 2019-11-29 at 17.13.52.png…]()

**Comment by otzbergnet** [comment]
I am not sure about the emojis, but I do think that the center align of the buttons is "driving me crazy", so I right aligned them and cheated a bit to get them to inset by a certain number of pixels. The look will be this:

![Bildschirmfoto 2019-11-29 um 20 05 25](https://user-images.githubusercontent.com/43129918/69886704-97b02100-12e3-11ea-8e7d-df50167ca700.png)

I quite prefer that over the center align of the previous look, as it kind of clean it up and makes it significantly less busy

**Comment by otzbergnet** [comment]
I will however say that you did a fab job picking emjois that would make sense in a charming way.

**Comment by gingerbeardman** [comment]
Left-aligned looked much better!

**Comment by gingerbeardman** [comment]
How about I create proper icons for the items. The emoji was to just give an idea. I would think they would all be single colour 16x16 icons like I do for toolbar.

**Comment by otzbergnet** [comment]
alright, monochrome icons certainly can work and they have the potential help users have some muscle memory with their selections.

16x16 sounds fine, I will need to adjust the width (and possibly the height) a bit late for some stupid not programming related reason ;) I kind of look forward to that, as it should be a good enhancement.

**Comment by gingerbeardman** [comment]
Icons (First Draft, may tweak or replace once in place)

- [Snapshot.pdf](https://github.com/otzbergnet/wbmExtension/files/3956153/Snapshot.pdf)
- [Calendar.pdf](https://github.com/otzbergnet/wbmExtension/files/3956146/Calendar.pdf)
- [Newest.pdf](https://github.com/otzbergnet/wbmExtension/files/3956149/Newest.pdf)
- [Oldest.pdf](https://github.com/otzbergnet/wbmExtension/files/3956150/Oldest.pdf)
- [Files.pdf](https://github.com/otzbergnet/wbmExtension/files/3956148/Files.pdf)
- [Data.pdf](https://github.com/otzbergnet/wbmExtension/files/3956147/Data.pdf)

Alternate icons for "save":
- [Pause.pdf](https://github.com/otzbergnet/wbmExtension/files/3956151/Pause.pdf)
- [Record.pdf](https://github.com/otzbergnet/wbmExtension/files/3956152/Record.pdf)
- [Stop.pdf](https://github.com/otzbergnet/wbmExtension/files/3956154/Stop.pdf)

Can we also tighten up the item spacing (button height) to make it look more like share menu?

**Comment by otzbergnet** [comment]
Good Evening,

I have added those icons and reduced the button height to 20px making things a bit tighter. Not sure it looks more like the share menu.

![Screenshot 2019-12-12 at 19 58 44](https://user-images.githubusercontent.com/43129918/70740636-d6999a00-1d19-11ea-99fa-53887032a754.png)

I need to think what to do with those icons in dark mode, I think I'll simply invert it for darkmode

![Screenshot 2019-12-12 at 20 00 17](https://user-images.githubusercontent.com/43129918/70740706-09dc2900-1d1a-11ea-960e-d7c04a68260b.png)
 
I might do that later

**Comment by otzbergnet** [comment]
![Screenshot 2019-12-12 at 20 06 19](https://user-images.githubusercontent.com/43129918/70741114-e796db00-1d1a-11ea-9fbf-b99cc054c063.png)

that looks a bit better in dark mode ;)

**Comment by gingerbeardman** [comment]
Ooh! Nice.

I'll do some minor tweaks today, and maybe try some alternate icons.

But I like it!

**Comment by gingerbeardman** [comment]
(you need to commit your changes)

**Comment by otzbergnet** [comment]
Everything should be committed - there are no uncommitted changes for me in GitHub Desktop - you sure they are not committed?

**Comment by otzbergnet** [comment]
Double checked and my commits are there. Please note one thing about the icons.

I am using some whitespace to the left to move the button in. I tried hard with an inset, but I couldn't get it to work and thus decided to cheat ;)

I am off this afternoon, so if you have anything you want me to look at, let me know. Otherwise I am working on getting the "Recommender from core.ac.uk" to work in OA Helper for iOS ;)

**Comment by gingerbeardman** [comment]
Got them thanks — user error "not enough coffee"

**Comment by gingerbeardman** [comment]
Text in menus is blue in non-Dark mode.

How do I put more space between the icon and the text?

**Comment by otzbergnet** [comment]
I need to come clean, I was unable to figure out the spacing, so I am simply going to suggest - simply add more "transparent space" in the image...

The text for me is black - what OS are you in?

**Comment by gingerbeardman** [comment]
Mojave 10.14.6

**Comment by otzbergnet** [comment]
mmmh, I might have to try on my other computer tomorrow then

**Comment by otzbergnet** [comment]
committed a change, that replaces .textColor with .windowFrameTextColor - haven't checked out the color in macOS 10.15 yet - but hope that things look "good" for you as well

**Comment by gingerbeardman** [comment]
Going to change the images soon, but I noticed they are not sharp pixels so I am wondering if there is a better size for them to be? Thoughts appreciated.

**Comment by otzbergnet** [comment]
I might have "ruined it", when I rescaled the images. I honestly don't know. However, if we wanted to submit the app soon, we best do it before the weekend, otherwise it will be a 2020 thing. I am quite ok with that, but just wanted to shape your expectations (App Store Connect will shut down for about a week over Christmas)

**Comment by gingerbeardman** [comment]
I'll the a look, but let's submit before that deadline.

I'm happy.

**Comment by otzbergnet** [comment]
Hi Matt,

I am somewhat confused about where we left things. Should we ship without new icons, or will you have time to create new ones? Sorry to be bugging you like this / I have no urgency to submit this, other than that I don't want this project to end up in an "unfinished" state :) After all I want our good work to shine ;)

**Comment by gingerbeardman** [comment]
Let's ship it! Time has run away from me.

**Comment by otzbergnet** [comment]
👍 I did submit it, far from perfect, but we can always update later. 
Should we not get to exchange any messages before the holidays: Happy Christmas, Happy Hanukkah, Happy New Year :)

**Comment by gingerbeardman** [comment]
And to you and yours my friend
