### ISSUE TITLE
[Discuss] Name of the App

### ISSUE THREAD

**Issue by otzbergnet** [otzbergnet/wbmExtension#18]
App Name & Sub-Title can be 30 characters each. This makes things a bit difficult. So how about

Wayback
simply the internet archive

I know it ain't great, but it picks up your suggestion of the app name @gingerbeardman and the subtitle might help convey the use a bit. I am very much looking forward to your suggestion

**Comment by gingerbeardman** [comment]
Yikes! That's a short limit.

I think you're on the right lines.

```
-------------30--------------
simply the internet archive
easy internet archive access
```

**Comment by otzbergnet** [comment]
Wayback
easy internet achive access

sounds like a winner to me :)

**Comment by gingerbeardman** [comment]
Decision made
