### ISSUE TITLE
1024x1024px PNG of toolbar icon needed for a App Icon

### ISSUE THREAD

**Issue by otzbergnet** [otzbergnet/wbmExtension#2]
In order to provide a consistent application icon, a 1024x1024px PNG of Toolbar Icon (with transparency) is desired

**Comment by gingerbeardman** [comment]
Here we go

![1024x1024](https://user-images.githubusercontent.com/49612/68999441-279fa500-08b8-11ea-9ac4-3d04c29b80d9.png)
