### ISSUE TITLE
[BUG] button overlay issues

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/wbmExtension#23]
Will look at this soon.

![Screen shot 2019-12-03 at 12 15 07](https://user-images.githubusercontent.com/49612/70050371-af7af400-15c6-11ea-9a82-ed5c0a193d8d.png)

**Comment by gingerbeardman** [comment]
Problem was on the site I was using, CSS was declared as:
![Screen shot 2019-12-03 at 12 22 06](https://user-images.githubusercontent.com/49612/70050759-9e7eb280-15c7-11ea-8287-b5d2cb0787a3.png)

So we will need to force CSS on this element using CSS from the extension.

**Comment by gingerbeardman** [comment]
Also, clickable area is not equal all the way around.

![Screen shot 2019-12-03 at 12 24 19](https://user-images.githubusercontent.com/49612/70050935-fb7a6880-15c7-11ea-929b-815a133dbf29.png)

**Comment by gingerbeardman** [comment]
Foxed in my recent PR

**Comment by otzbergnet** [comment]
nice :) Thanks!
