### ISSUE TITLE
[Discuss] - do we want keyboard shortcuts and what should they be

### ISSUE THREAD

**Issue by otzbergnet** [otzbergnet/wbmExtension#3]
Do we want keyboard shortcuts for the feature set of the extension and if so, what should they be?

We need to consider not interfering with keyboard shortcuts popular web applications use and that are easy and intuitive

**Comment by gingerbeardman** [comment]
Tab Space uses Control shortcuts to avoid the crowded Cmd shortcut space.

https://joyuer.cn/Tab-Space/?ref=github-wbmExtension

> Shortcuts for Safari which offer the long missing function:
> Ctrl + L – Close left tabs
> Ctrl + R – Close right tabs
> Ctrl + Q – Close all other tabs
> Ctrl + D – Duplicate current tab
> Ctrl + C – Open in Chrome
> Ctrl + F – Open in Firefox
> Ctrl + T – Open Tab Space
> Ctrl + B – Save selected text to Bear, finally you have a Web Clipper for Safari

So maybe we could continue that and go for <kbd>Ctrl</kbd> + <kbd>W</kbd>?

**Comment by otzbergnet** [comment]
ctrl + w = will open page history - I will have a play implementing this :)

**Comment by otzbergnet** [comment]
So I added ctrl + w for the page history, however I also put it in in such a way, that we can let the user customize the shortcut that they want

I console.log the shortcut that is being used, so if a user were to look at the console in Safari s/he would be able to know. I am thinking of adding the shortcut to the context menu as well - wonder, what you think whether that should be listed as ^+w or ctrl+w // the former certainly be the proper macOS way, but more and more users have no clue what that means and some Apple keyboards only show ctrl these days

**Comment by otzbergnet** [comment]
I also added an "easy"-ish way to set your own preferred shortcut letter- requiring ctrl, but allowing users to set their own. We can surely iterate on this, but hopefully this is good enough of a starting point

**Comment by gingerbeardman** [comment]
I'll take a look soon
