### ISSUE TITLE
Menu is not dismissed after choosing item

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/wbmExtension#30]
repropduce
1. open menu
1. choose "show page history" (for example)

expected
1. open in new tab
1. menu should close

actual
1. open in new tab
1. menu stays open

previously the menu would close when selecting an item (not sure when it changed)

**Comment by otzbergnet** [comment]
Thank you - I'll look into this in the next few days.

**Comment by otzbergnet** [comment]
I submitted this to the App Store this morning, should get released in a few days (at most). Closing for now
