### ISSUE TITLE
There's a bug where the history total is not overwritten from a previous tab if there is no history result with the current tab

### ISSUE THREAD

**Issue by otzbergnet** [otzbergnet/wbmExtension#31]
There's a bug where the history total is not overwritten from a previous tab if there is no history result with the current tab:

click WBM icon on a tab with history results (shows number)
click WBM icon on a tab with no history results (bug: shows same number)
click WBM icon again on same tab with no history results (correctly shows no number)

**Comment by otzbergnet** [comment]
@gingerbeardman this will be fixed with the next release. Very sorry for the stupidity of this case.

**Comment by gingerbeardman** [comment]
Not to worry! It's not a big deal.

**Comment by otzbergnet** [comment]
I submitted this to the App Store this morning, should get released in a few days (at most). Closing for now
