### ISSUE TITLE
[Discuss] - Do we want to support multilingual?

### ISSUE THREAD

**Issue by otzbergnet** [otzbergnet/wbmExtension#4]
Does it make sense to support Multilingual for this app? As always, I am more than happy to provide a German version ;) Although I must say that it will be hard to translate this in a meaningful way

**Comment by gingerbeardman** [comment]
I'm OK with us going for English only until there is demand? After all Wayback Machine itself I believe is English only?

What do you think? 

Why difficult to translate it in a meaningful way? If a German user had experience with Wayback enough to install this extension surely they would understand the menu items?

**Comment by otzbergnet** [comment]
I've given it some more thought and I'll put in a German translation... 

Translating an app is a tougher problem than it might seem, as you need to use fairly short commands. So the problem really boils down to knowing the right terminology and that requires someone, who uses the feature set within the community. The German language is prone to the use of anglicisms, which can make translations sound terrible to the "uninitiated", but if you are in the community and use those terms all the time, it is far more "intuitive"
