### ISSUE TITLE
How did you not get "ReferenceError: Can't find variable: safari"?

### ISSUE THREAD

**Issue by Daniyaldehleh** [otzbergnet/wbmExtension#44]
Hi there,

Sorry to bother you out of nowhere,

I was really curious to know how you didn't get:

`ReferenceError: Can't find variable: safari` error as my team & I have been running to this constantly no matter our effort. We even added:
    "nativeMessaging" to permissions.

**Comment by otzbergnet** [comment]
Hi @Daniyaldehleh ,

I take it that this isn't an error report with this extension and I will therefore close.

It is really hard to troubleshoot your report without more details. Feel free to contact me at claus.wolf@otzberg.net and provide some more details.

Unless you have a very special use case, I would suggest that you try utilising Web Extensions, they are very easy to convert, if you have a working Chrome/Firefox extension and will safe you costs (as you only need to develop a single extension) and use multiple places.

Happy Christmas
