### ISSUE TITLE
[Discuss] - behavior of commands

### ISSUE THREAD

**Issue by otzbergnet** [otzbergnet/wbmExtension#5]
I decided to offer different behavior for each command, depending on whether a user is on the Wayback Machine already.

Imagine you are viewing shapshot X of website Y and you click the "open newest snapshot", it will first parse the URL from the Wayback Machine's URL and use the site's url to action the request.

Is that the right behavior? To me anything else would have felt like we invite recurrsive behavior

**Comment by gingerbeardman** [comment]
Yes, correct!
