### ISSUE TITLE
[Discuss] - minimum macOS version

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/wbmExtension#6]
I've reduced this to 10.14, limited by use of TintColor in the code.

Ideally it would be great if we could lower to 10.13 but we'll have to find an alternative colour mechanism that works OK in Dark Mode, etc.

**Comment by otzbergnet** [comment]
That's a big one :( 

Wasn't dark mode introduced with Mojave (10.14)? Do you have a 10.13 machine around for testig?

**Comment by gingerbeardman** [comment]
I don't, but previously I used named system colours that toggled in dark mode. 

I take a look soon

**Comment by gingerbeardman** [comment]
have committed a small 10.14 change straight to master

**Comment by otzbergnet** [comment]
I would vote, at this time, if neither of us has a macOS 10.13 machine, that we close it and move on... I know, not a popular thing to say...

**Comment by gingerbeardman** [comment]
Yes, OK

**Comment by gingerbeardman** [comment]
I have to keep resetting this to 10.14, not sure why?

![Screen shot 2019-11-22 at 21 10 53](https://user-images.githubusercontent.com/49612/69460665-94111d00-0d6c-11ea-9290-9b5be5b18074.png)

**Comment by gingerbeardman** [comment]
Ignore me, my fault I had not updated to latest changes
