### ISSUE TITLE
[Discuss] - behaviour of toolbar button

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/wbmExtension#7]
As I previously described, my old extension offered the following functionality, largely due to the way legacy Safari extensions worked:

- click toolbar button: do "Show Newest Snapshot"
- click and hold toolbar button: show context menu (to make a different choice)
- context menu: do "Show Page History"

Is there a mechanism to to the click vs click and hold this in the new world?

My use case is most often i just want to see a snapshot of the page (like i can do with the context menu, but I need it for the current page not a link) and I use a quick click of the toolbar to do that. Less frequently I want to use the other features of the menu.

I guess a keyboard shortcut could do this, but maybe there is also a GUI way?

**Comment by otzbergnet** [comment]
In Safari App Extensions - so my understanding, you must make a decision between whether you want the Toolbar Button to be clicked and have an action (my Open Access Helper) does that, or you have the popover, but you cannot have both at the same time, at least I am not familiar with that.

So we should definitely do the keyboard shortcuts, and I propose adding a second context menu item just to give both feature sets.

I'll also change the label of the context menu to match the Show Newest Snapshot & Show Page History actions for clarity

**Comment by gingerbeardman** [comment]
That's a good compromise!

**Comment by gingerbeardman** [comment]
What bout installing 2 toolbar buttons, but only one activating at install.

One would offer the full menu (as we have)

The other would offer only one-click-to-archive (Show Page History)

**Comment by otzbergnet** [comment]
I think only a single toolbar icon can be installed, however it sounds like a user configurable setting and that we could do. I need to play with this, but the goal would be to hijack the clicked toolbar button, before it will draw. Sounds like a viewWillAppear type function. It could issue a command and return and be done with it. Let me have a play with this

**Comment by gingerbeardman** [comment]
I believe you can have more then one toolbar items? https://developer.apple.com/documentation/safariservices/safari_app_extensions/safari_app_extension_info_property_list_keys/about_contextual_menu_and_toolbar_item_keys

**Comment by otzbergnet** [comment]
I fear we need to go down my idea, because the documentation you linked, clearly states:

> Each app extension can have only one toolbar item. 

To be fair, it would be most confusing and wasteful to allow more. After all each App Extension fights for space that is extremely limited.

**Comment by otzbergnet** [comment]
Just a quick update - I didn't get much time to work on this this week - but the little experimenting I did, has not left me with a good feeling of being able to achieve this ;( Rather sad about it... I haven't given up though

**Comment by otzbergnet** [comment]
I have tried a ton of things and while I was able to get close, my biggest problem is that the popover would "flash" for a second... I am out of ideas here, it obviously isn't something the good guys at Apple have considered. I am pretty sure that developers smarter than me (that'd be pretty much anyone) would figure it out, but I am willing to admit defeat on this one. I would personally suggest we drop it for now

**Comment by gingerbeardman** [comment]
Yes, let's drop it.

I'm training my muscles to do <kbd>Control</kbd>+<kbd>w</kbd> :)

**Comment by otzbergnet** [comment]
So here is a thought:

What, if we didn't actually use the popover and gave users the option to use the button to action, or inject an div into the page with the other functions?

I think I personally would prefer the the popover, but we could use an injected div to get the behavior you are looking for. 

I think it now boils down to "how much do you want that behavior", because if that is the way we want to go down, it wouldn't take a ton of work.

**Comment by otzbergnet** [comment]
Or rather... why not inject a little button in the bottom right of the page (fixed position) so that you can click there. It might make more sense to have just that one button there, as a user customizable feature. I'll quickly mock this up to see if that'd work for you

**Comment by otzbergnet** [comment]
![Bildschirmfoto 2019-11-26 um 20 32 28](https://user-images.githubusercontent.com/43129918/69666167-1dd22a80-108c-11ea-9169-ab5b954db196.png)

You get to set it by checking "yes" to a setting question. It is small, always there and shouldn't bein the way.

![Bildschirmfoto 2019-11-26 um 20 34 24](https://user-images.githubusercontent.com/43129918/69666190-26c2fc00-108c-11ea-82d2-3d3d988a6a71.png)

What do you think?

**Comment by otzbergnet** [comment]
@gingerbeardman  how do you feel about the proposed solution here? I kind of start to get used to the little "archive" icon in my bottom left :)

**Comment by gingerbeardman** [comment]
I only just built latest version with my changes so will live with rid for a day or so.

**Comment by otzbergnet** [comment]
Sorry to have been rushing you :(

**Comment by gingerbeardman** [comment]
Not at all, I should have installed it sooner

**Comment by gingerbeardman** [comment]
This is a cool option!

The only thing I would say is that it could be a fraction tighter to the corner, so that the status bar covers it centrally vertically.

Move left 4 units and down 4 units.

![Screen shot 2019-12-01 at 17 23 16](https://user-images.githubusercontent.com/49612/69917603-9146b400-145f-11ea-9758-0e01a298758a.png)

![Screen shot 2019-12-01 at 17 23 22](https://user-images.githubusercontent.com/49612/69917604-91df4a80-145f-11ea-8fde-1f50c99ec9b7.png)

current, overlaid:

![dupe](https://user-images.githubusercontent.com/49612/69917625-d7037c80-145f-11ea-86d1-d658fbb2ec64.png)

**Comment by gingerbeardman** [comment]
I'd also make the icon larger than the pixel area, with some blank padding so that it is, say, 32x32 in total size (with the 16x16 image in the middle) so it's an easier target to click.

**Comment by otzbergnet** [comment]
I went with 24x24 square at the location you have specified. It does however get covered up by the status bar complete. I think it looks quite alright now ;)

![Screenshot 2019-12-01 at 18 43 49](https://user-images.githubusercontent.com/43129918/69917821-88a7ab00-146a-11ea-98a8-17dcd20a31fb.png)

**Comment by gingerbeardman** [comment]
Let's roll with it!

I still need to build with the left aligned item change and then I'll put some icons in then we can make a decision on launch?
