### ISSUE TITLE
[Discuss] - "enter address" text field

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/wbmExtension#8]
I see the official WBM extension has a text field you can type or paste in URLs. This means you can remove one step from going to wayback and then typing or pasting in a URL.

Might be useful.

Will look at UI soon

**Comment by otzbergnet** [comment]
I've quickly added this - terribly UI for now, but we can fix that later, I guess

**Comment by gingerbeardman** [comment]
I paste in a URL and press enter but... nothing?

**Comment by otzbergnet** [comment]
Could you provide your test case? Did you include http or https?

**Comment by gingerbeardman** [comment]
Seems to work now, will keep an eye one it!

**Comment by gingerbeardman** [comment]
Ah, yes, maybe I did not include http or https

**Comment by otzbergnet** [comment]
So I think we hit two problems:

1) I ought to allow URLs without protocol to be submitted
2) I ought to implement something that will explain why the entry was rejected

Something for tomorrow or the day after

**Comment by otzbergnet** [comment]
This should be fixed now. I say these things with conviction, but realize how wrong I likely am ;)

**Comment by gingerbeardman** [comment]
I have messed up the translation of the URL code. Please fix.

I think it should say www.example.com as the Placeholder.

![Screen shot 2019-12-03 at 15 43 31](https://user-images.githubusercontent.com/49612/70066210-37232b80-15e4-11ea-88e9-b2d45a5d5d30.png)

**Comment by otzbergnet** [comment]
I fixed the www.example.com - however I do have a question. Especially when seen on a dark background it is apparent how the menu entries are of a much lighter color than the "this page was never archived" or "Enter a URL to go to archive" page. Should this really be the case?

![Screenshot 2019-12-03 at 20 34 56](https://user-images.githubusercontent.com/43129918/70084620-ec6ad900-160e-11ea-9f45-2a86c74e96f1.png)

**Comment by gingerbeardman** [comment]
I'm not sure why they are that colour. Maybe because they are buttons?

They should be dark like the label.

**Comment by otzbergnet** [comment]
Turns out, it is very much down to the transparency effect that is applied to the popover. Now makes me wonder, if I should change the background of the popover or simply accept that this is a bit of an optical illusion in some cases. I did double- and triple-check that they all use "labelColor"

**Comment by gingerbeardman** [comment]
I think just leave it if it's standard macOS behaviour.

**Comment by otzbergnet** [comment]
perfect, I'll close the issue again
